# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# This workflow will build a Java project with Maven
name: Java CI # название Workflow

on: [push] # запуск push

jobs: # исполняемые задачи
  build: # сборка
    runs-on: ubuntu-latest # тип рубочей ОС

    steps: # шаги выполнения
      - uses: actions/checkout@v2 # выкачиваем репо
      - name: Set up JDK 11
        uses: actions/setup-java@v1 # установка JDK
        with:
          java-version: 11 # версия рабочей Java
      - name: Build with Maven
        run: mvn -B -e verify # запуск Maven
